# Generated by Django 3.0.3 on 2021-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birth_day',
            field=models.DateField(),
        ),
    ]
